# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  PYO3_USE_ABI3_FORWARD_COMPATIBILITY: "1"

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14", "3.15-dev"]

    steps:
    - uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      continue-on-error: ${{ matrix.python-version == '3.15-dev' }}
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      uses: abatilo/actions-poetry@v4
    - name: Install dependencies
      run: poetry install
    - name: Lint and format with Ruff
      run: |
        poetry run ruff check .
        poetry run ruff format . --check
    - name: Test no PDL_API_KEY
      run: poetry run pytest -k "not test_api_endpoint_"
    - name: Test with PDL_API_KEY
      run: poetry run pytest -k "test_api_endpoint_"
      env:
        PDL_API_KEY: ${{ secrets.PDL_API_KEY }}
